.github/workflows/ci.yaml
backend/constants.mo
cli/declarations/main/main.did.d.ts
frontend/declarations/main/main.did.d.ts
frontend/package-lock.json
package-lock.json
package.json

https://github.com/ZenVoich/mops/issues/46
CI/CD workflows to:
- Build and deploy the frontend
- Run the linter on the frontend and cli directories

Setting up CI/CD workflows

---

.github/workflows/ci-production-cli.yaml
.github/workflows/ci.yaml
README.md
backend/main/main-canister.mo
backend/main/types.mo
cli/declarations/main/main.did
cli/declarations/main/main.did.d.ts
cli/declarations/main/main.did.js
cli/templates/mops-test.yml
frontend/components/App.svelte
frontend/components/Package.svelte
frontend/components/PackageCard.svelte
frontend/components/TopPackages.svelte
frontend/declarations/main/main.did
frontend/declarations/main/main.did.d.ts
frontend/declarations/main/main.did.js
frontend/package.json
package.json
test/.deep/gg/mops.toml

Show dependencies, dependents and version history on frontend

---

.github/workflows/ci-production-cli-node14.yaml
.github/workflows/ci-production-cli.yaml
.github/workflows/ci.yaml
.github/workflows/mops-test.yml
cli/commands/test.js
cli/templates/mops-test.yml

add wasi mode support to ‘mops test’

---

cli/commands/mmf1.js
cli/commands/test.js

[cli] run tests in parallel

---

cli/commands/mmf1.js
cli/commands/test.js

[cli] test: show failed line with adjacent lines

---

.eslintrc.json
backend/main/main-canister.mo
backend/utils.mo
cli/commands/search.js
cli/declarations/main/main.did
cli/declarations/main/main.did.d.ts
cli/declarations/main/main.did.js
frontend/components/Home.svelte
frontend/components/SearchResults.svelte
frontend/declarations/main/main.did
frontend/declarations/main/main.did.d.ts
frontend/declarations/main/main.did.js

All packages

---

cli/commands/import-identity.js
cli/mops.js

change config/cache folders

---

.github/workflows/mops-test.yml
cli/mops.js

add cache to workflow 'mops-test'

---

backend/main/main-canister.mo
cli/declarations/main/main.did
cli/declarations/main/main.did.d.ts
cli/declarations/main/main.did.js
frontend/components/Home.svelte
frontend/components/PackagesByCategory.svelte
frontend/declarations/main/main.did
frontend/declarations/main/main.did.d.ts
frontend/declarations/main/main.did.js

show packages by category

---

README.md
cli/README.md
cli/cli.ts
cli/commands/init.ts
cli/commands/template.ts
cli/package-lock.json
cli/package.json
cli/templates/README.md
cli/templates/licenses/Apache-2.0
cli/templates/licenses/Apache-2.0-NOTICE
cli/templates/licenses/MIT
cli/templates/src/lib.mo
cli/templates/test/lib.test.mo
frontend/components/docs/InstallDoc.svelte
package.json

CLI init wizard

---

.github/workflows/ci.yml
.github/workflows/mops-test.yml
backend/main/main-canister.mo
backend/main/types.mo
cli/cli.ts
cli/commands/available-updates.ts
cli/commands/outdated.ts
cli/commands/update.ts
cli/declarations/main/main.did
cli/declarations/main/main.did.d.ts
cli/declarations/main/main.did.js
frontend/declarations/main/main.did
frontend/declarations/main/main.did.d.ts
frontend/declarations/main/main.did.js
package.json

Add CLI commands `outdated` and `update`

---

backend/main/main-canister.mo
backend/main/types.mo
cli/cli.ts
cli/commands/publish.ts
cli/commands/test/mmf1.ts
cli/commands/test/reporters/compact-reporter.ts
cli/commands/test/reporters/silent-reporter.ts
cli/commands/test/reporters/verbose-reporter.ts
cli/commands/test/test.ts
cli/declarations/main/main.did
cli/declarations/main/main.did.d.ts
cli/declarations/main/main.did.js
frontend/components/Package.svelte
frontend/components/PackageRightPanel.svelte
frontend/declarations/main/main.did
frontend/declarations/main/main.did.d.ts
frontend/declarations/main/main.did.js
test/.hello/test/lib.test.mo
test/.hello/test/suite.test.mo
test/.hello/test/test.mo

Feature: package test stats

---

backend/main/download-log.mo
backend/main/main-canister.mo
mops.toml
test/download-log.test.mo
test/download-trend.test.mo

Use datetime package

---

backend/main/main-canister.mo
cli/cli.ts
cli/commands/transfer-ownership.ts
cli/declarations/main/main.did
cli/declarations/main/main.did.d.ts
cli/declarations/main/main.did.js
frontend/declarations/main/main.did
frontend/declarations/main/main.did.d.ts
frontend/declarations/main/main.did.js

Transfer ownership

---

backend/main/validate-config.mo
cli/commands/add.ts
cli/commands/install.ts
cli/commands/update.ts
cli/mops.ts
cli/vessel.ts

GitHub package commit hash

---

cli/commands/install-all.ts
cli/commands/install-local.ts
cli/commands/install.ts
cli/declarations/main/main.did
cli/declarations/main/main.did.d.ts
cli/declarations/main/main.did.js
cli/resolve-packages.ts
frontend/declarations/main/main.did
frontend/declarations/main/main.did.d.ts
frontend/declarations/main/main.did.js
test/.flat/aaa/mops.toml
test/.flat/ccc/mops.toml
test/.hello/mops.toml

Transitive local dependencies

---

backend/main/PackagePublisher.mo
backend/main/main-canister.mo
backend/main/registry/Registry.mo
backend/main/registry/getPackageChanges.mo
backend/main/registry/getPackageDetails.mo
backend/main/registry/packagesByCategory.mo
backend/main/types.mo
backend/main/utils/package-utils.mo
cli/cli.ts
cli/commands/bench-replica.ts
cli/commands/bench.ts
cli/commands/publish.ts
cli/commands/test/test.ts
cli/declarations/bench/bench.did.d.ts
cli/declarations/main/main.did
cli/declarations/main/main.did.d.ts
cli/declarations/main/main.did.js
docs/docs/cli/2-publish/01-mops-publish.md
frontend/components/ColorizedValue.svelte
frontend/components/package/Package.svelte
frontend/components/package/PackageBenchmark.svelte
frontend/components/package/PackageBenchmarks.svelte
frontend/components/package/PackageBenchmarksDiff.svelte
frontend/components/package/PackageVersionSummary.svelte
frontend/declarations/bench/bench.did.d.ts
frontend/declarations/main/main.did
frontend/declarations/main/main.did.d.ts
frontend/declarations/main/main.did.js
frontend/index.html
frontend/logic/benchmark-utils.ts

Publish package benchmarks

---

backend/main/PackagePublisher.mo
backend/main/main-canister.mo
backend/main/registry/Registry.mo
backend/main/registry/getPackageChanges.mo
backend/main/registry/getPackageDetails.mo
backend/main/registry/searchInRegistry.mo
backend/main/types.mo
backend/main/utils/validateConfig.mo
cli/check-requirements.ts
cli/commands/add.ts
cli/commands/install-all.ts
cli/commands/publish.ts
cli/commands/toolchain/index.ts
cli/declarations/bench/bench.did.d.ts
cli/declarations/bench/index.js
cli/declarations/main/index.js
cli/declarations/main/main.did
cli/declarations/main/main.did.d.ts
cli/declarations/main/main.did.js
cli/mops.ts
cli/types.ts
docs/docs/09-mops.toml.md
frontend/components/package/PackageRightPanel.svelte
frontend/declarations/bench/bench.did.d.ts
frontend/declarations/bench/index.js
frontend/declarations/main/index.js
frontend/declarations/main/main.did
frontend/declarations/main/main.did.d.ts
frontend/declarations/main/main.did.js
test/.hello/mops.toml

Package requirements

---

cli/bin/moc-wrapper.sh

[cli] optimize `moc-wrapper`

---

docs/docs/how/00-version-package.md
docs/docs/how/01-how-dependecy-resolution-works.md
docs/docs/how/_category_.json

Docs update
